#!/usr/bin/env python3
"""
Minimal persistent workspace generator for PortaCode workshops.
It collects a pairing code, device prefix, and student count, then
creates per-student folders, writes docker-compose.yaml + .env, and
starts the containers.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import List

if sys.version_info < (3, 10):
    sys.stderr.write(
        "generate_classroom.py requires Python 3.10 or newer.\n"
        "Please rerun with `python3 generate_classroom.py`.\n"
    )
    sys.exit(1)

BASE_DIR = Path(__file__).resolve().parent
STUDENTS_DIR = BASE_DIR / "students"
COMPOSE_FILE = BASE_DIR / "docker-compose.yaml"
ENV_FILE = BASE_DIR / ".env"
STATE_FILE = BASE_DIR / "classroom_state.json"

DEFAULT_GATEWAY = "wss://portacode.com/gateway"
DEFAULT_PREFIX = "Workshop-Device"


@dataclass
class Student:
    index: int
    slug: str
    device_name: str
    service_name: str
    host_path: Path


def prompt(text: str, *, default: str | None = None, required: bool = False) -> str:
    while True:
        suffix = f" [{default}]" if default else ""
        value = input(f"{text}{suffix}: ").strip()
        if not value and default:
            value = default
        if required and not value:
            print("Please provide a value.")
            continue
        return value


def prompt_int(text: str, *, default: int | None = None, minimum: int = 1) -> int:
    while True:
        suffix = f" [{default}]" if default is not None else ""
        raw = input(f"{text}{suffix}: ").strip()
        if not raw and default is not None:
            return default
        try:
            value = int(raw)
        except ValueError:
            print("Enter a whole number.")
            continue
        if value < minimum:
            print(f"Value must be >= {minimum}.")
            continue
        return value


def slugify(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-")
    slug = cleaned.lower()
    return slug or "device"


def split_prefix(prefix: str) -> tuple[str, int]:
    trimmed = prefix.strip()
    match = re.search(r"(\d+)$", trimmed)
    if match:
        width = len(match.group(1))
        base = trimmed[: match.start()].rstrip("-_ ")
        return (base or "device", width)
    return (trimmed or "device", 2)


def ensure_docker_compose() -> None:
    try:
        subprocess.run(
            ["docker", "compose", "version"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            "Docker Compose plugin is required. Make sure `docker compose` works "
            "before running this script."
        ) from exc


def create_student_dirs(students: List[Student]) -> None:
    for student in students:
        student.host_path.mkdir(parents=True, exist_ok=True)
        os.chmod(student.host_path, 0o777)


def write_env_file(pairing_code: str, gateway: str) -> None:
    content = textwrap.dedent(
        f"""\
        # Generated by generate_classroom.py
        PORTACODE_GATEWAY={gateway}
        PORTACODE_PAIRING_CODE={pairing_code}
        """
    )
    ENV_FILE.write_text(content)


def build_compose_yaml(students: List[Student]) -> str:
    lines = ["services:"]
    for student in students:
        host_rel = os.path.relpath(student.host_path, BASE_DIR).replace("\\", "/")
        lines.extend(
            [
                f"  {student.service_name}:",
                "    build:",
                "      context: .",
                "    image: portacode/workshop-device-persistent:latest",
                f"    hostname: {student.service_name}",
                "    environment:",
                "      PORTACODE_GATEWAY: ${PORTACODE_GATEWAY}",
                "      PORTACODE_PAIRING_CODE: ${PORTACODE_PAIRING_CODE}",
                f"      PORTACODE_DEVICE_NAME: {json.dumps(student.device_name)}",
                "    volumes:",
                f"      - ./{host_rel}:/home/student/workspace",
                "    restart: unless-stopped",
            ]
        )
    return "\n".join(lines) + "\n"


def write_state_file(
    students: List[Student], pairing_code: str, device_prefix: str, gateway: str
) -> None:
    state = {
        "pairing_code": pairing_code,
        "device_prefix": device_prefix,
        "gateway": gateway,
        "students": [
            {
                "device_name": s.device_name,
                "service_name": s.service_name,
                "workspace": os.path.relpath(s.host_path, BASE_DIR),
            }
            for s in students
        ],
    }
    STATE_FILE.write_text(json.dumps(state, indent=2))


def docker_compose_up() -> None:
    try:
        subprocess.run(
            ["docker", "compose", "up", "-d"],
            check=True,
            cwd=BASE_DIR,
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            "docker compose up -d failed. Fix the error above and rerun the script."
        ) from exc


def main() -> None:
    ensure_docker_compose()

    print(
        textwrap.dedent(
            """
            === PortaCode Persistent Workspace ===
            This script collects a few inputs and provisions all student containers.
            """
        ).strip()
    )

    pairing_code = prompt("PortaCode pairing code", required=True)
    device_prefix = prompt(
        "Device name prefix", default=DEFAULT_PREFIX, required=True
    )
    num_students = prompt_int("Number of student containers", default=3, minimum=1)
    gateway = prompt("PortaCode gateway URL", default=DEFAULT_GATEWAY, required=True)

    base_label, number_width = split_prefix(device_prefix)
    students: List[Student] = []
    slug_prefix = slugify(base_label)
    for idx in range(1, num_students + 1):
        number = f"{idx:0{number_width}d}"
        slug = f"{slug_prefix}-{number}"
        device_name = f"{base_label}-{number}" if base_label else number
        students.append(
            Student(
                index=idx,
                slug=slug,
                device_name=device_name,
                service_name=slug,
                host_path=STUDENTS_DIR / slug / "workspace",
            )
        )

    create_student_dirs(students)
    write_env_file(pairing_code, gateway)
    COMPOSE_FILE.write_text(build_compose_yaml(students))
    write_state_file(students, pairing_code, device_prefix, gateway)
    docker_compose_up()

    print("\nAll containers are starting!")
    print("Use `docker compose ps` to see status, `docker compose down` to stop.\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user.")
